name: Deploy til Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Sett opp Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Logg inn på Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Logg inn på Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Bygg og push backend-image
      run: |
        cd backend
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-api:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-api:${{ github.sha }}
    
    - name: Bygg og push frontend-image
      run: |
        cd frontend
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-app:${{ github.sha }} .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-app:${{ github.sha }}
    
    - name: Deploy backend til Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kioversikt-api'
        images: ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-api:${{ github.sha }}
    
    - name: Deploy frontend til Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kioversikt-app'
        images: ${{ secrets.ACR_LOGIN_SERVER }}/kioversikt-app:${{ github.sha }}
    
    - name: Logg ut fra Azure
      run: |
        az logout 